name = "computer-ell-dev"
main = "src/index.tsx"
compatibility_date = "2025-01-15"
assets = { directory = "./public", binding = "ASSETS"}
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "ea9596c42fa24e45aaac873e42ee5402"

[vars]
DOMAIN = "computer.ell.dev"
CLIENT_ID = "ellgapp"
REDIRECT_URI = "https://computer.ell.dev/auth/redirect"
TWITCH_REDIRECT_URI = "https://computer.ell.dev/twitch/auth/redirect"
TWITCH_CLIENT_ID = "xahn2w6b6fov6c5qga22kr1sn0t2pw"

[observability.logs]
enabled = true

[triggers]
crons = ["0 * * * *"]